apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: kafka-sigma-engine
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: rule-engine
        kubernetes_sd_configs:
          - role: pod
            namespaces:
              names: [kafka-sigma-engine]
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_label_app]
            action: keep
            regex: rule-engine
          - source_labels: [__meta_kubernetes_pod_ip]
            target_label: __address__
            replacement: "$1:8001"
          - source_labels: [__meta_kubernetes_pod_name]
            target_label: pod

      - job_name: prometheus
        static_configs:
          - targets: [localhost:9090]
