apiVersion: v1
kind: Service
metadata:
  name: log-generator
  namespace: kafka-sigma-engine
spec:
  type: LoadBalancer
  selector:
    app: log-generator
  ports:
    - port: 8080
      targetPort: 8080
