[mypy]
python_version = 3.11
strict = True
ignore_missing_imports = True

[mypy-aiokafka.*]
ignore_missing_imports = True

[mypy-elasticsearch.*]
ignore_missing_imports = True

[mypy-prometheus_client.*]
ignore_missing_imports = True

[mypy-yaml.*]
ignore_missing_imports = True
