apiVersion: apps/v1
kind: Deployment
metadata:
  name: rule-engine
  namespace: kafka-sigma-engine
spec:
  replicas: 4
  selector:
    matchLabels:
      app: rule-engine
  template:
    metadata:
      labels:
        app: rule-engine
    spec:
      containers:
        - name: rule-engine
          image: kafka-sigma-engine/rule-engine:latest
          imagePullPolicy: Never
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: kafka:9092
            - name: SIGMA_RULES_DIR
              value: /app/sigma_rules
            - name: METRICS_PORT
              value: "8001"
            - name: WORKER_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          ports:
            - containerPort: 8001
              name: metrics
          resources:
            requests:
              cpu: 250m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 128Mi
